-- Create notes table
CREATE TABLE IF NOT EXISTS public.notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create orders table
CREATE TABLE IF NOT EXISTS public.orders (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    line_order_no TEXT UNIQUE NOT NULL,
    line_status TEXT NOT NULL,
    payment_status TEXT NOT NULL,
    payment_method TEXT,
    internal_status TEXT NOT NULL DEFAULT 'PENDING',
    customer_name TEXT NOT NULL,
    customer_line_uid TEXT,
    order_date DATE NOT NULL,
    checkout_at TIMESTAMPTZ,
    subtotal_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    shipment_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    total_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    remark_buyer TEXT,
    rejection_reason TEXT,
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create order_items table
CREATE TABLE IF NOT EXISTS public.order_items (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    sku TEXT,
    barcode TEXT,
    name TEXT NOT NULL,
    price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discounted_price NUMERIC(12, 2),
    quantity INTEGER NOT NULL DEFAULT 1,
    image_url TEXT,
    variants JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create evidence table
CREATE TABLE IF NOT EXISTS public.evidence (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK (type IN ('photo', 'video')),
    storage_path TEXT NOT NULL,
    public_url TEXT NOT NULL,
    uploaded_by TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create line_customer_map table
CREATE TABLE IF NOT EXISTS public.line_customer_map (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    line_uid TEXT UNIQUE NOT NULL,
    display_name TEXT,
    customer_name TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Optional but recommended)
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.line_customer_map ENABLE ROW LEVEL SECURITY;

-- Simple public read access for notes (to fix the home page error)
CREATE POLICY "Public read access for notes" ON public.notes FOR SELECT USING (true);
